language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - pip install .[plot]
  - pip install pytest flake8
script:
  - cd tests && MATPLOTLIBRC="../ci" ./tests.sh
  - flake8 src
cache: pip
